apiVersion: v1
kind: Service
metadata:
  name: mock-upstream
  namespace: inference-gateway-mock
  labels:
    app: mock-upstream
spec:
  selector:
    app: mock-upstream
  ports:
    - name: http
      port: 18081
      targetPort: http
