apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm

resources:
  - namespace.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - jaeger-deployment.yaml
  - jaeger-service.yaml
  - otel-collector-configmap.yaml
  - otel-collector-deployment.yaml
  - otel-collector-service.yaml
  - gateway-ingress.yaml

images:
  - name: inference-serving-gateway
    newName: 012345678901.dkr.ecr.us-east-1.amazonaws.com/inference-serving-gateway
    newTag: aws-dev-latest

patches:
  - path: gateway-patch.yaml
  - path: observability-patch.yaml
